### ISSUE TITLE
[FEATURE] create a paste with a language

### ISSUE THREAD

**Issue by CodeMyst** [YilianSource/brackeys-bot#234]
**Why do you want this feature? What is the problem?**
currently if a codeblock is marked with a language, it won't be used to create the paste in the correct language.

**Describe the solution you'd like**
get the language of the codeblock and use that to fill the `language` field for the paste.

**Comment by YilianSource** [comment]
Not possible currently, due to a limitation with language naming.

PasteMyst will return a BadRequest if it doesn't know the language, which is an issue since `cs` is a valid language alias for `csharp` in Markdown.

The change is implemented in #236, but we will only merge once the limitation is eliminated.
