### ISSUE TITLE
[FEATURE] Detection of "How to"

### ISSUE THREAD

**Issue by ANF-Studios** [YilianSource/brackeys-bot#256]
**Why do you want this feature? What is the problem?**
A lot of people ask how to do this, or how to do that. And it becomes a burden to run the `[]google` or `[]ddg` or ~~`[]bing`~~ command.

**Describe the solution you'd like**
So, to solve this problem. You can check if the content of the message starts with how to, and if this returns as true, the bot can then automatically reply that. At least for the development and help section. This feature can or cannot be useful.

**Comment by YilianSource** [comment]
I could see this becoming more of a nuisance than a genuine help.

The `[]google` command was made to be a friendly reminder for people to search for their question on Google first, instead of blatantly asking. If we automate this process, we could get false positives, which would just annoy people.

As for it becoming a burden: No one is obligated to respond to someone wanting help. If we automate the help process to harshly, the process of helping someone becomes unpersonal and stiff, which is something we want to avoid at all costs.

One could argue that the simple existance of these custom helper commands contradicts that, but those are meant as more of a timesaver once a personal helper is already established.

**Comment by ANF-Studios** [comment]
I never thought it that way and I agree. Thanks for the time!
