### ISSUE TITLE
[FEATURE] productive mute

### ISSUE THREAD

**Issue by harshhhdev** [YilianSource/brackeys-bot#268]
*Why do you want this feature? What is the problem?*

Often times people are too distracted from Discord, and may find themselves struggling to keep away from the server.

*Describe the solution you'd like*

Add a !productivemute command, which allows a user to mute themselves for a specified amount of time (ideally, should make the max amount something like 24 hours so the user doesn't start begging mods to unmute)

**Comment by YilianSource** [comment]
I can really only see downsides to this. If they mute themselves here, they might just aswell go into another server to type. And the entire point of muting themselves is a bit flawed, because the most efficient way of muting yourself is to _just close Discord_.

I really can't see myself adding this, it seems like more of a meme than something that is of actual value. Can't really have users minimodding themselves using the bot.

**Comment by harshhhdev** [comment]
Understood, yeah if they mute themselves on one they’ll just go talk in another.
