### ISSUE TITLE
Runtime compilation feature

### ISSUE THREAD

**Issue by YilianSource** [YilianSource/brackeys-bot#66]
For example, []compile will compile the last sent codeblock for any syntax errors that can be identified.

Feedback on the idea is very welcomed.

**Comment by CodeMyst** [comment]
That wouldn't really work because a lot of scripts will depend on the UnityEngine or UnityEditor assembly.

You could get them by compiling a blank unity project but I'm not sure it will work. The project is a .Net Core project and Unity is .Net Standard 4.x (there might be a .Net Framework 2.0 which you can use with .Net Core but I'm not sure if unity has that). So you'd need to create bindings.

This is definitely a good idea, need further investigation.

**Comment by YilianSource** [comment]
That's true. What about syntax checking? Syntax checking is possible without other assemblies AFAIK.

**Comment by CodeMyst** [comment]
Syntax checking is pretty trivial. Now that I think about, just compiling code wouldn't be really useful either since the one posting the code block would notice them in their editor / unity / terminal.

**Comment by MetalBreaker** [comment]
Unity doesn't have .Net Standard 4.x. In fact, .NET Standard 4.x doesn't even exist.
Unity has three options:
.NET Framework 3.5
.NET Framework 4.6
.NET Standard 2.0
The third one is usable with .NET Core. Just saying :p

**Comment by CodeMyst** [comment]
I missed up Framework and Standard :P

**Comment by MetalBreaker** [comment]
The issue should be closed in my opinion.
